name: Go Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Run tests
      run: |
        go list ./... | xargs -I {} sh -c 'go test -v {} || [ $? -eq 5 ]'
